name: Export Markdown Files

on:
  workflow_dispatch:  # manuell auslösbar

jobs:
  export-md:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # - name: Install dependencies
        # run: pip install -r scripts/requirements.txt

      - name: Extract Markdown files
        run: python lib/tasks/extract_markdown.py

      - name: Upload Markdown output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: markdown-files
          path: _data/

